#!/usr/bin/env bash
set -euo pipefail

docker run --rm \
  -v /etc/letsencrypt:/etc/letsencrypt \
  -v /var/lib/letsencrypt:/var/lib/letsencrypt \
  -v /var/log/letsencrypt:/var/log/letsencrypt \
  -v /var/www/4u/current:/var/www/4u/current \
  certbot/certbot:latest renew --preferred-profile shortlived --quiet
nginx -t
systemctl reload nginx
