// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4n3o8437h65x8i6.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG4zbzg0MzdoNjV4OGk2IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODc1MTY4NDksImV4cCI6MjEwMzA5Mjg0OX0.WJHyAJUfwrWB7g6J-PZXCxcQ5E-B7_almi_ALYtTPXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
